.so ../man_macros/suds_man_macros
.TH XXX 2 "6 February 1994" "suds \*v" "SUDS SUBROUTINE"
.SH NAME
xxx \- does whatever
.SH C_SYNOPSIS
.ft B
#include <suds/suds.h>
.br
.sp 0.5
.nf
int xxx(string,list)
char *string;
struct codes *list;
.fi.ft R
.SH FORTRAN_SYNOPSIS
.ft B
.nf
integer*4 xxx
function xxx(string,list)
	character*(*) string;
	integer*4 list;
.fi
.ft R
.SH DESCRIPTION
.SH AUTHOR
Peter L. Ward, U.S. Geological Survey, Menlo Park, CA 94025
