.so ../man_macros/suds_man_macros
.TH FOCALMECH 5 "6 February 1994" "pc_suds" "PC_SUDS STRUCTURE"
.SH NAME
focalmech \- general information about a focal mechanism
.SH SYNOPSIS
.nf
.ta 0.7i +1.4i +0.7i +0.7i +0.7i +0.7i +0.7i +0.7i +0.7i
.ft B
typedef	struct {
	FIXED	structure_type;
	FIXED	structure_len;
	FLOAT4	astrike;
	FLOAT4	adip;
	FLOAT4	arake;
	FLOAT4	bstrike;
	FLOAT4	bdip;
	FLOAT4	brake;
	CHAR	prefplane;
	CHAR	spareC;
	INT2	spareD;
	PAD4	pad_K;
} PCSUDS_FOCALMECH;
.sp 0.5
#define PC_FOCALMECH	16L
.fi
.ft R
.SH DESCRIPTION
Not commonly used in PC-SUDS.
.SH MEMBERS
.TP
\fBstructure_type\fI structure type\fR
Define number of this type of structure.
.TP
\fBstructure_len\fI structure length\fR
Length of this structure in bytes.
.TP
\fBastrike\fI strike of a\fR
.BB
index_string=true
.EB
.TP
\fBadip\fI dip of a\fR
.TP
\fBarake\fI rake of a\fR
.TP
\fBbstrike\fI strike of b\fR
.TP
\fBbdip\fI dip of b\fR
.TP
\fBbrake\fI rake of b\fR
.TP
\fBprefplane\fI preferred plane\fR
Preferred plane a or b.
.BB
allow_char="ab"
.EB
.TP
\fBspareC\fI for future use\fR
.TP
\fBspareD\fI for future use\fR
.TP
\fBpad_K\fI padding\fR
.SH "SEE ALSO"
