.so ../man_macros/suds_man_macros
.TH XXX 5 "6 February 1994" "pc_suds" "PC_SUDS STRUCTURE"
.SH NAME
xxx \- 
.SH SYNOPSIS
.nf
.ta 0.7i +1.4i +0.7i +0.7i +0.7i +0.7i +0.7i +0.7i +0.7i
.ft B
typedef struct {
} PCSUDS_XXX;
.sp 0.5
#define PCXXXS	0L
.fi
.ft R
.SH DESCRIPTION
.BB
.EB
.SH MEMBERS
.TP
\fBstructure_type\fI structure type\fR
Define number of this type of structure.
.TP
\fBstructure_len\fI structure length\fR
Length of this structure in bytes.
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fB\fI \fR
.TP
\fBspare\fI for future use\fR
.SH "SEE ALSO"
