.so ../man_macros/suds_man_macros
.TH TIMECORRECTION 5 "8 February 1994" "pc_suds" "PC_SUDS STRUCTURE"
.SH NAME
timecorrection \- time correction information
.SH SYNOPSIS
.nf
.ta 0.7i +1.4i +0.7i +0.7i +0.7i +0.7i +0.7i +0.7i +0.7i
.ft B
typedef	struct {
	FIXED	structure_type;
	FIXED	structure_len;
	FIXED	len_netn_J;
	STRING	network[4];
	FIXED	len_st_nam_J;
	STRING	st_name[5];
	CODE1	component;
	CODE2	inst_type;
	PAD4	pad_P;
	FLOAT8	time_correct;
	FLOAT4	rate_correct;
	CODE1	sync_code;
	CHAR	program;
	PAD2	pad_Q;
	ST_TIME	effective_time;
	INT2	spareM;
	PAD2	pad_B;
} PCSUDS_TIMECORRECTION;
.sp 0.5
#define PC_TIMECORRECTION	30L
.fi
.ft R
.SH DESCRIPTION
Commonly used in PC-SUDS.
.SH MEMBERS
.TP
\fBstructure_type\fI structure type\fR
Define number of this type of structure.
.TP
\fBstructure_len\fI structure length\fR
Length of this structure in bytes.
.TP
\fBlen_netn_J\fI len net name\fR
.TP
\fBnetwork\fI network name\fR
.TP
\fBlen_st_nam_J\fI len stat name\fR
.TP
\fBst_name\fI station name\fR
.BB
index_string=true
.EB
.TP
\fBcomponent\fI component\fR
.BB
codelist=comps
.EB
.TP
\fBinst_type\fI instrument type\fR
.BB
codelist=inst_type
.EB
.TP
\fBpad_P\fI padding\fR
.TP
\fBtime_correct\fI time correction\fR
Time correction to be added to begintime.
.TP
\fBrate_correct\fI rate correction\fR
Rate correction to be added to rate.
.TP
\fBsync_code\fI synchonization\fR
Synchronization code.
.BB
codelist=syncs
.EB
.TP
\fBprogram\fI program\fR
.TP
\fBpad_Q\fI padding\fR
.TP
\fBeffective_time\fI time effective\fR
Time this correction was calculated.
.TP
\fBspareM\fI for future use\fR
.TP
\fBpad_B\fI padding\fR
.SH "SEE ALSO"
