.so ../man_macros/suds_man_macros
.TH TERMINATOR 3 "17 April 1994" "suds \*v" "SUDS STRUCTURE"
.SH NAME
terminator \- structure to end a group of structures in a stream
.SH C_SYNOPSIS
.nf
.ta 0.7i +1.4i +0.7i +0.7i +0.7i +0.7i +0.7i +0.7i +0.7i
.ft B
typedef struct {
	FIXED	structure_type;
	FIXED	structure_len;
	INT4	structure_num; 
	INT4	spare;
	REFERS2	comment_id;
	DOMAIN	comment_dc;
} SUDS_TERMINATOR;
.sp 0.5
#define TERMINATORS	213L
.fi
.ft R
.SH DESCRIPTION
Structure to end a group of structures in a stream.
.SH MEMBERS
.TP
\fBstructure_type\fI structure type\fR
Define number of this type of structure, i.e. 2.
.TP
\fBstructure_len\fI structure length\fR
Length of this structure in bytes.
.TP
\fBstructure_num\fI structure number\fR
Number of the structure type that began this sequence.
.BB
index_string=true
.EB
.TP
\fBspare\fI for future use\fR
.TP
\fBcomment_id\fI comment\fR
.so ../man_macros/comment_id.descrip
.BB
key=part_foreign(1,comment.comment_id), db_delete=nullify
.EB
.TP
\fBcomment_dc\fI comment domain\fR
Domain in which comment_id is unique.
.BB
codelist=authorities, key=part_foreign(1,comment.comment_dc), db_delete=nullify
.EB
.SH "SEE ALSO"

